friend/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

gitbig/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

import login.urls as login
import profiles.urls as profile
import friend.urls as friend
import history.urls as history

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(login, namespace='login')),
    url(r'^profile/', include(profile, namespace='profile')),
    url(r'^friend/', include(friend, namespace='friend')),
    url(r'^history/', include(history, namespace='history')),
    url(r'^$', RedirectView.as_view(url='login/', permanent=True), name='index'),
]

login/urls.py
from django.conf.urls import url
from .views import index, profile, add_item_to_database, delete_status
from .custom_auth import auth_login, auth_logout


urlpatterns = [
    url(r'^$', index, name='index'),
	url(r'^profile/', profile, name='profile'),

    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),


	url(r'^add_status/', add_item_to_database, name='add_status'),
	url(r'^delete/(?P<id>\d+)/', delete_status, name='delete'),
 ]

friend/models.py
from django.db import models

# Create your models here.
class Expertise(models.Model):
    NAME = (
        ('Python', 'Python'),
        ('Java', 'Java'),
        ('C#', 'C#'),
        ('Kotlin', 'Kotlin'),
        ('Erlang', 'Erlang'),
    )

    LEVEL = (
        (1, 'Beginner'),
        (2, 'Intermediate'),
        (3, 'Advanced'),
        (4, 'Expert'),
        (5, 'Legend'),
    )

    COLOR = (
        (1, '#aed3ef'),
        (2, '#75aaff'),
        (3, '#4892f9'),
        (4, '#6eb7ef'),
        (5, '#4784b2'),
    )

    name = models.TextField(choices=NAME)
    level = models.IntegerField(choices=LEVEL)
    color = models.IntegerField(choices=COLOR, default='Blue')

    def __str__(self):
    	return 'Expertise:' + self.name

class Friend(models.Model):
    name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250, unique=True)
    year = models.CharField(max_length=4)
    expertise = models.ManyToManyField(Expertise)

friend/views.py
from django.shortcuts import render
from .models import Friend

response = {}
def index(request):
    response['author'] = "gitgud"
    friends = Friend.objects.all()
    response['friends'] = friends
    return render(request, 'friend/friend.html', response)

friend/templates/friend/friend.html
{% load staticfiles %}
{% load static %}
{% block content %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/universal.css' %}" />
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>

<div class="wrapper">
<input type="text" id="myInput" onkeyup="search()" placeholder="Search by name..." title="Type in a name">
<div>
  <input id="input0" type="radio" name="filter" value="0"> NPM
  <input id="input1" type="radio" name="filter" value="1"> Name
  <input id="input2" type="radio" name="filter" value="2"> Year
  <input id="input3" type="radio" name="filter" value="3"> Expertise
  <input id="input4" type="radio" name="filter" value="4"> Level
</div>
<table id="myTable">
  <tr class="header">
    <th style="width:20%;">NPM</th>
    <th style="width:40%;">Name</th>
    <th style="width:10%;">Year</th>
    <th style="width:10%;">Expertise</th>
    <th hidden style="width:10%;">Level</th>
    <!-- <th style="width:10%;"></th> -->
  </tr>

  {% for i in friends %}
    <tr>
        <td> {{i.npm}} </td>
        <td> {{i.name}} </td>
        <td> {{i.year}} </td>
        <td>
        {% for expertise in i.expertise.all %}
            <div class="expertise" style='background-color:{{ expertise.get_color_display }}'>
                <!-- <p id="level" hidden> {{ expertise.level }} </p> -->
                <!-- <script>changeColor(document.getElementById("level").innerHTML)</script> -->
                {{ expertise.name }}
            </div>
        {% endfor %}
        </td>
        <td hidden>
        {% for expertise in i.expertise.all %}
            {{ expertise.get_level_display }}
        {% endfor %}
        </td>
        <!-- <td> <button class="button-add">+</button> </td> -->
    </tr>
  {% endfor %}
</table>
</div>

<script>

$("#input0").on("click", function () {
   $('#myInput').attr('placeholder', "Search by NPM...").val("").focus().blur();
});

$("#input1").on("click", function () {
   $('#myInput').attr('placeholder', "Search by name...").val("").focus().blur();
});

$("#input2").on("click", function () {
   $('#myInput').attr('placeholder', "Search by year...").val("").focus().blur();
});

$("#input3").on("click", function () {
   $('#myInput').attr('placeholder', "Search by expertise...").val("").focus().blur();
});

$("#input4").on("click", function () {
   $('#myInput').attr('placeholder', "Search by level...").val("").focus().blur();
});


function search() {
    var input, filter, table, tr, td, i, value, radios;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    table = document.getElementById("myTable");
    tr = table.getElementsByTagName("tr");
    radios = document.getElementsByName('filter');

    value = 1; //initial value 0: search by name

    for (var i = 0, length = radios.length; i < length; i++)
    {
        if (radios[i].checked)
        {
            value = parseInt(radios[i].value);
        break;
        }
    }

    for (i = 0; i < tr.length; i++) {
        td = tr[i].getElementsByTagName("td")[value];
        if (td) {
          if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
            tr[i].style.display = "";
          } else {
            tr[i].style.display = "none";
          }
        }
    }
}

</script>

{% endblock %}