gitbig/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

import login.urls as login
import profiles.urls as profile
import friend.urls as friend
import history.urls as history

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(login, namespace='login')),
    url(r'^profile/', include(profile, namespace='profile')),
    url(r'^friend/', include(friend, namespace='friend')),
    url(r'^history/', include(history, namespace='history')),
    url(r'^$', RedirectView.as_view(url='login/', permanent=True), name='index'),
]

login/urls.py
from django.conf.urls import url
from .views import index, profile, add_item_to_database, delete_status
from .custom_auth import auth_login, auth_logout


urlpatterns = [
    url(r'^$', index, name='index'),
	url(r'^profile/', profile, name='profile'),

    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),


	url(r'^add_status/', add_item_to_database, name='add_status'),
	url(r'^delete/(?P<id>\d+)/', delete_status, name='delete'),
 ]

profiles/urls.py
from django.conf.urls import url
from .views import index, edit_profile, save_profile, delete_expertise, save_profile_before, get_profile
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^edit/$', edit_profile, name='edit_profile'),
    url(r'^save/$', save_profile, name='save_profile'),
    url(r'^get/$', get_profile, name='get_profile'),
    url(r'^save_before/$', save_profile_before, name='save_profile_before'),
    url(r'^delete_expertise/(?P<id>\d+)/', delete_expertise, name='delete_expertise'),
]

friend/models.py
from django.db import models

# Create your models here.
class Expertise(models.Model):
    NAME = (
        ('Python', 'Python'),
        ('Java', 'Java'),
        ('C#', 'C#'),
        ('Kotlin', 'Kotlin'),
        ('Erlang', 'Erlang'),
    )

    LEVEL = (
        (1, 'Beginner'),
        (2, 'Intermediate'),
        (3, 'Advanced'),
        (4, 'Expert'),
        (5, 'Legend'),
    )

    COLOR = (
        (1, '#aed3ef'),
        (2, '#75aaff'),
        (3, '#4892f9'),
        (4, '#6eb7ef'),
        (5, '#4784b2'),
    )

    name = models.TextField(choices=NAME)
    level = models.IntegerField(choices=LEVEL)
    color = models.IntegerField(choices=COLOR, default='Blue')

    def __str__(self):
    	return 'Expertise:' + self.name

class Friend(models.Model):
    name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250, unique=True)
    year = models.CharField(max_length=4)
    expertise = models.ManyToManyField(Expertise)

profiles/models.py
from __future__ import unicode_literals
from django.db import models


# Create your models here.

profiles/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
import requests
from friend.models import Expertise, Friend
from login.models import Human
import json
# Create your views here.
response = {}

def index(request):
    set_data_for_session(response, request)
    return render(request, 'profiles/profile.html', response)

def set_data_for_session(res, request):
    response['author'] = request.session['user_login']
    response['kode_identitas'] = request.session['kode_identitas']
    # response['name'] = request.session['name']
    if 'email' in request.session:
        response['name'] = request.session['name']
        response['email'] = request.session['email']
        response['linkedin'] = request.session['linkedin']
        response['picture'] = request.session['picture']
        response['score'] = request.session['score']
    else:
        response['picture'] = "https://www.idlidu.com/Content/images/default.png"
        response['score'] = "1"

    expertise = get_expertise_from_database(request)
    response['expertise'] = expertise
    response['numOfExpertise'] = expertise.count()

def edit_profile(request):
    set_data_for_session(response, request)
    return render(request, 'profiles/editProfile.html', response)

# def list_status(request):
#     #  Implement this function by yourself
#     get_data_session(request)
#     status = []
#     if get_data_human(request, 'user_login'):
#         status = get_my_message_from_database(request)
#     print(status)
#     response['status'] = status

def get_expertise_from_database(request):
    resp = []
    # npm = get_data_human(request, 'kode_identitas')
    npm = request.session['kode_identitas']
    human = Human.objects.get(npm=npm)
    expertise = human.expertise.all()
    return expertise

# def get_data_session(request):
#     if get_data_human(request, 'user_login'):
#         response['author'] = get_data_human(request, 'user_login')
#
# def get_data_human(request, tipe):
#     data = None
#     if tipe == "user_login" and 'user_login' in request.session:
#         data = request.session['user_login']
#     elif tipe == "kode_identitas" and 'kode_identitas' in request.session:
#         data = request.session['kode_identitas']
#     return data

def delete_expertise(request, id):
    npm = request.session['kode_identitas']
    human = Human.objects.get(npm = npm)
    expertise = human.expertise.filter(pk=id)
    expertise.delete()
    return HttpResponseRedirect(reverse('profile:edit_profile'))

@csrf_exempt
def save_profile_before(request):
    if request.method == 'POST':
        request.session['score'] = request.POST['score']
        response['score'] = request.session['score']

        expertise = json.loads(request.POST['expertise']) #array of expertise
        level = json.loads(request.POST['level']) #array of level
        npm = request.session['kode_identitas']
        human = Human.objects.get(npm=npm)
        human.expertise.all().delete()
        for i in range(len(expertise)):
            human.expertise.add(Expertise.objects.create(name=expertise[i], level=level[i], color=level[i]))

        human.score = request.session['score']
        human.save()

    return JsonResponse({'redirect_url': '/login/'})

@csrf_exempt
def get_profile(request):
    if request.method == 'GET':
        response['score'] = request.session['score']
        return JsonResponse(response)

@csrf_exempt
def save_profile(request):
    if request.method == 'POST':
        request.session['name'] = request.POST['name']
        request.session['email'] = request.POST['email']
        request.session['linkedin'] = request.POST['linkedin']
        request.session['picture'] = request.POST['picture']
        request.session['score'] = request.POST['score']
        response['name'] = request.session['name']
        response['email'] = request.session['email']
        response['linkedin'] = request.session['linkedin']
        response['picture'] = request.session['picture']
        response['score'] = request.session['score']

        expertise = json.loads(request.POST['expertise']) #array of expertise
        level = json.loads(request.POST['level']) #array of level
        npm = request.session['kode_identitas']
        human = Human.objects.get(npm=npm)
        human.expertise.all().delete()
        for i in range(len(expertise)):
            human.expertise.add(Expertise.objects.create(name=expertise[i], level=level[i], color=level[i]))

        human.name = request.session['name']
        human.email = request.session['email']
        human.linkedin = request.session['linkedin']
        human.picture = request.session['picture']
        human.score = request.session['score']
        human.save()

    return JsonResponse({'redirect_url': '/login/'})

profiles/templates/profiles/editProfile.html
{% extends "login/layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block content %}
<!----------------------------- INIT SDK ---------------------------->
<head>
    <script type="text/javascript" src="//platform.linkedin.com/in.js">
        api_key:   81ejezfyunfj2y
        onLoad: onLinkedInLoad
        authorize: true
        lang:      en_US
        scope: r_basicprofile r_emailaddress
    </script>
</head>

<!----------------------------- BODY ---------------------------->
<body>
    <div class='wrapper'>
    <div class="content-wrapper">
        <br>
        <br>
        <button class="button" style='margin-right: 30px;' onClick=exitProfile() id="exit"></button>
        <button class="button" onClick=saveProfileBefore() id="save"></button>
        <section class="profile-header" id="profile-header">
        </section>
        <br/>
        <br/>
        <p id='personal-data'></p>
        <section class="section-profile-table">
            <div class="profile-table" id="profile-table">
                <script type="in/Login"></script>
                <table align='left' style='text-align: left' id="table">
                </table>
            </div>
        </section>
        <br>
        <br>
        <p id='expertise'></p>
        <div class="keahlian-baru"></div>
        <br>
        <button class="button-expertise" id="add-expertise" onclick="addExpertise()"></button>
        <br>
        <br>
        <br>
        <p id="show-score"></p>
        <div class="radio-button">
        </div>
        <br>
        <br>
    </div>
  </div>
</body>

<script>
function onLinkedInLoad() {
    if(IN.User.isAuthorized()){
        getProfile();
    }
    else{
        $('#profile-header').html(
        '<img id="img" class="img-circle" src="https://www.idlidu.com/Content/images/default.png" style="height:120px;widht:120px"/>'
        + '<br><br>'
        + '<p>{{kode_identitas}}</p>');

        $('#save').attr('onClick', 'saveProfileBeforeLogin()');

        render();
        IN.Event.on(IN, "auth", getProfile);
    }
}

function getProfile() {
  IN.API.Profile('me').fields([
    'first-name', 'last-name',
    'public-profile-url',
    'picture-urls::(original)',
    'email-address'
    ])
  .result(displayProfiles);
}

var name, picture, email, linkedin;
var numOfExpertise = {{ numOfExpertise }};

function displayProfiles(profiles) {
  console.log(profiles)
  var member = profiles.values[0];

  picture = member.pictureUrls.values[0];
  name = member.firstName + " " + member.lastName;
  email = member.emailAddress;
  linkedin = member.publicProfileUrl;

  $('#profile-header').html(
  '<img id="img" class="img-circle" src="' + picture + '" style="height:120px;widht:120px"/>'
  + '<br><br>'
  + '<p>{{kode_identitas}}</p>');

  $('#table').html(
      "<tr>"
          + "<td class='col'>Name</td>"
          + "<td class='col'>"
              + name
          + "</td>"
      + "</tr>"
      + "<tr>"
          + "<td class='col'>Email</td>"
          + "<td class='col'>"
               + email
          + "</td>"
      + "</tr>"
      + "<tr>"
          + "<td class='col'>LinkedIn Profile</td>"
          + "<td class='col'>"
               + '<a href={{linkedin}} target="_blank">' + linkedin + '</a>'
          + "</td>"
      + "</tr>");

     $('.section-profile-table').append('<p><a id="logout-link" href="javascript:void(0);" onclick="logout()">Change LinkedIn Profile</a></p>')

     $('#save').attr('onClick', 'saveProfile()');
     render();
}

function logout(){
      IN.User.logout(removeProfileData);
}

function removeProfileData(){
    $('#table').remove();
    $('#logout-link').remove();
}

function render(){
    console.log("kesini")
    $('#personal-data').html('Personal Data');
    $('#show-score').html('Show Score');
    $('#expertise').html('Expertise');
    $('#save').html('Save');
    $('#exit').html('Exit');
    $("#add-expertise").html('Add Expertise');
    $('.button').css('background-color', '#e8e8e8');
    $('.button-expertise').css('background-color', '#e8e8e8');

    $('.keahlian-baru').append(
        '{% for i in expertise %}<table id="table-exp"><td><label style="padding-right:5px;" for="keahlian">Skills:</label>'
        + '<select name="keahlian" class="skillNew" data-id="{{forloop.counter}}">'
            + '<option value="Java">Java</option>'
            + '<option value="C#">C#</option>'
            + '<option value="Python" >Python</option>'
            + '<option value="Erlang">Erlang</option>'
            + '<option value="Kotlin">Kotlin</option>'
        + '</select></td>'
        + '<td><label style="padding-right:5px;" for="level" style="margin-left:30px;">Level:</label>'
        + '<select name="level" class="levelNew" data-id="{{forloop.counter}}">'
            + '<option value="1">Beginner</option>'
            + '<option value="2">Intermediate</option>'
            + '<option value="3" >Advance</option>'
            + '<option value="4">Expert</option>'
            + '<option value="5">Legend</option>'
        + '</select></td>' + '<td><a href="{% url "profile:delete_expertise" i.id %}" class="btn btn-danger">-</a></td></table>{%endfor%}')

    $('.radio-button').html(
        '<input id="input0" type="radio" name="score" value="0"> Yes'
        + '<input id="input1" type="radio" name="score" value="1"> No')

}

function addExpertise(){
    $('.keahlian-baru').append(
        '<table id="table-exp"><td><label style="padding-right:5px;" for="keahlian">Skills:</label>'
        + '<select name="keahlian" class="skillNew" data-id="{{forloop.counter}}">'
            + '<option value="Java">Java</option>'
            + '<option value="C#">C#</option>'
            + '<option value="Python" >Python</option>'
            + '<option value="Erlang">Erlang</option>'
            + '<option value="Kotlin">Kotlin</option>'
        + '</select></td>'
        + '<td><label style="padding-right:5px;" for="level" style="margin-left:30px;">Level:</label>'
        + '<select name="level" class="levelNew" data-id="{{forloop.counter}}">'
            + '<option value="1">Beginner</option>'
            + '<option value="2">Intermediate</option>'
            + '<option value="3" >Advance</option>'
            + '<option value="4">Expert</option>'
            + '<option value="5">Legend</option>'
        + '</select></td>' + '<td><a href="{% url "profile:edit_profile" %}" class="btn btn-danger">-</a></td></table>')
};

function saveProfileBeforeLogin(){
    //////////////////////////expertise/////////////////////////
    var expertise = [];
    var level = [];

    $('.skillNew').each(function(i, obj) {
        var value = $(this).val();
        expertise.push(value);
    });

    $('.levelNew').each(function(i, obj) {
        var value = $(this).val();
        level.push(value);
    });

    console.log(expertise)
    console.log(level)

    //////////////////////////radio/////////////////////////
    var radios = document.getElementsByName('score');

    var show_score = 0; //initial value 0: search by name

    for (var i = 0, length = radios.length; i < length; i++)
    {
        if (radios[i].checked)
        {
            show_score = parseInt(radios[i].value);
        break;
        }
    }

    //////////////////////////post/////////////////////////
    $.ajax({
         method: "POST",
         url: '{% url "profile:save_profile_before" %}',
         data: {
             'expertise': JSON.stringify(expertise),
             'level': JSON.stringify(level),
             'score': show_score,
         },
         dataType: 'json',
         success: function (response) {
             window.location.href = response.redirect_url;
         },
         error : function (error) {
             console.log(error.responseText)
         }
     });
}

function saveProfile(){
    //////////////////////////expertise/////////////////////////
    var expertise = [];
    var level = [];

    $('.skillNew').each(function(i, obj) {
        var value = $(this).val();
        expertise.push(value);
    });

    $('.levelNew').each(function(i, obj) {
        var value = $(this).val();
        level.push(value);
    });

    console.log(expertise)
    console.log(level)

    //////////////////////////radio/////////////////////////
    var radios = document.getElementsByName('score');

    var show_score = 0; //initial value 0: search by name

    for (var i = 0, length = radios.length; i < length; i++)
    {
        if (radios[i].checked)
        {
            show_score = parseInt(radios[i].value);
        break;
        }
    }

    //////////////////////////post/////////////////////////
    $.ajax({
         method: "POST",
         url: '{% url "profile:save_profile" %}',
         data: {
             'name': name,
             'email': email,
             'linkedin': linkedin,
             'picture': picture,
             'expertise': JSON.stringify(expertise),
             'level': JSON.stringify(level),
             'score': show_score,
         },
         dataType: 'json',
         success: function (response) {
             window.location.href = response.redirect_url;
         },
         error : function (error) {
             console.log(error.responseText)
         }
     });
}

function exitProfile(){
    window.location.href = '/login/'
}

$(".dropdown").html(
    '<a href="#" class="dropdown-toggle" data-toggle="dropdown">'
    + '<img src={{picture}} class="profile-image img-circle" style="height:30px;width:30px"><b class="caret"></b></a>'
    + '<div class="dropdown-content">'
    + '<a href="{% url "login:auth_logout" %}" onclick="return confirm("Logout?")"> Logout </a>'
    + '</div>'
)
</script>
{% endblock %}

profiles/templates/profiles/profile.html
{% load staticfiles %}
{% load static %}
{% block content %}
<head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/universal.css' %}" />
</head>
<div class="wrapper">
<div class="profile-table">
    <table align="left" style="text-align: left">
        <tr>
            <td class='col'>Name</td>
            <td class='col'>{% if name %} {{ name }}{% else %} Empty{% endif %}</td>
        </tr>
        <tr>
            <td class='col'>NPM</td>
            <td class='col'>{{kode_identitas}}</td>
        </tr>
        <tr>
            <td class='col'>Expertise</td>
            <td class='col'>
            {% if expertise %}
                {% for i in expertise %}
                    <div class="expertise" style='background-color:{{ i.get_color_display }}'>
                        {{ i.name }}
                    </div>
                {% endfor %}
            {% else %}
                Empty
            {% endif %}
            </td>
        </tr>
        <tr>
            <td class='col'> Email</td>
            <td class='col'>{% if email %} {{ email }}{% else %} Empty{% endif %}</td>
        </tr>
        <tr>
            <td class='col'>LinkedIn Profile</td>
            <td class='col'>{% if linkedin %} <a href={{linkedin}} target="_blank">{{linkedin}}</a> {% else %} Empty{% endif %}</td>
        </tr>
    </table>
</div>
</div>

{% endblock %}