gitbig/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

import login.urls as login
import profiles.urls as profile
import friend.urls as friend
import history.urls as history

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(login, namespace='login')),
    url(r'^profile/', include(profile, namespace='profile')),
    url(r'^friend/', include(friend, namespace='friend')),
    url(r'^history/', include(history, namespace='history')),
    url(r'^$', RedirectView.as_view(url='login/', permanent=True), name='index'),
]

login/urls.py
from django.conf.urls import url
from .views import index, profile, add_item_to_database, delete_status
from .custom_auth import auth_login, auth_logout


urlpatterns = [
    url(r'^$', index, name='index'),
	url(r'^profile/', profile, name='profile'),

    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),


	url(r'^add_status/', add_item_to_database, name='add_status'),
	url(r'^delete/(?P<id>\d+)/', delete_status, name='delete'),
 ]

profiles/urls.py
from django.conf.urls import url
from .views import index, edit_profile, save_profile, delete_expertise, save_profile_before, get_profile
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^edit/$', edit_profile, name='edit_profile'),
    url(r'^save/$', save_profile, name='save_profile'),
    url(r'^get/$', get_profile, name='get_profile'),
    url(r'^save_before/$', save_profile_before, name='save_profile_before'),
    url(r'^delete_expertise/(?P<id>\d+)/', delete_expertise, name='delete_expertise'),
]

login/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from friend.models import Expertise, Friend

# Create your models here.
class Human(models.Model):
    npm	 = models.CharField('Kode Identitas', max_length=20, primary_key=True, )
    name = models.CharField('Nama', max_length=200)
    email = models.CharField(max_length=200, default="")
    linkedin = models.CharField(max_length=200, default="")
    loggedin =  models.BooleanField(default=False)
    expertise = models.ManyToManyField(Expertise)
    friends = models.ManyToManyField(Friend)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Status(models.Model):
	human = models.ForeignKey(Human)
	date = models.DateTimeField(auto_now_add=True)
	message = models.TextField()

profiles/models.py
from __future__ import unicode_literals
from django.db import models


# Create your models here.

login/forms.py
from django import forms

class Status_Form(forms.Form):
	error_messages = {
		'required': 'Please fill in the input',
	}
	attrs = {
		'class': 'form-control',
		'rows':4,
		'cols':10,
		'style':'width:85%;',
	}

	status = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True, label="")

login/views.py
# Create your views here.
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .models import Human, Status
from .forms import Status_Form

response = {}

# NOTE : untuk membantu dalam memahami tujuan dari suatu fungsi (def)
# Silahkan jelaskan menggunakan bahasa kalian masing-masing, di bagian atas
# sebelum fungsi tersebut.

# ======================================================================== #
# User Func
# Apa yang dilakukan fungsi INI? #silahkan ganti ini dengan penjelasan kalian
def index(request):
    print ("#==> masuk index")
    if 'user_login' in request.session:
        return HttpResponseRedirect(reverse('login:profile'))
    else:
        response['author'] = get_data_human(request, 'user_login')
        html = 'login/session/login.html'
        return render(request, html, response)

def profile(request):
    print ("#==> profile")
    if 'user_login' not in request.session.keys():
        response['author'] = get_data_human(request, "user_login")
        html = 'login/session/login.html'
        return render(request, html, response)
    else:
        set_data_for_session(request)
        kode_identitas = get_data_human(request, 'kode_identitas')
        try:
            human = Human.objects.get(npm = kode_identitas)
        except Exception as e:
            human = create_new_human(request)

        response['Status_form'] = Status_Form
        if Status.objects.filter(human=human).count()>0:
            request.session['stat_last'] = Status.objects.filter(human=human).last().message
            response['stat_last'] = request.session['stat_last']
        else:
            request.session['stat_last'] = "No Status yet!"
            response['stat_last'] = request.session['stat_last']

        response['user_login'] = request.session['user_login']
        response['title'] = 'Status'
        response['jumlah_status'] = human.status_set.count()
        list_status(request)
        html = 'login/session/profile.html'
    return render(request, html, response)

def set_data_for_session(request):
    response['author'] = get_data_human(request, 'user_login')
    response['kode_identitas'] = request.session['kode_identitas']
    response['role'] = request.session['role']

    if 'email' in request.session:
        response['name'] = request.session['name']
        response['email'] = request.session['email']
        response['linkedin'] = request.session['linkedin']
        response['picture'] = request.session['picture']
        response['score'] = request.session['score']
    else:
        response['picture'] = "https://www.idlidu.com/Content/images/default.png"
        response['score'] = "1"

def list_status(request):
    #  Implement this function by yourself
    get_data_session(request)
    status = []
    if get_data_human(request, 'user_login'):
        status = get_my_message_from_database(request)
    print(status)
    response['status'] = status

def get_my_message_from_database(request):
    resp = []
    npm = get_data_human(request, 'kode_identitas')
    human = Human.objects.get(npm=npm)
    items = Status.objects.filter(human=human)
    resp = items
    return resp

def get_data_session(request):
    if get_data_human(request, 'user_login'):
        response['author'] = get_data_human(request, 'user_login')

def create_new_human(request):
    name = get_data_human(request, 'user_login')
    npm = get_data_human(request, 'kode_identitas')
    human = Human()
    human.npm = npm
    human.name = name
    human.save()
    return human

def get_data_human(request, tipe):
    data = None
    if tipe == "user_login" and 'user_login' in request.session:
        data = request.session['user_login']
    elif tipe == "kode_identitas" and 'kode_identitas' in request.session:
        data = request.session['kode_identitas']
    return data

def add_item_to_database(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST'):
        npm = get_data_human(request, 'kode_identitas')
        human = Human.objects.get(npm = npm)

        status = Status()
        status.message = request.POST['message']
        status.human = human
        status.save()
    return HttpResponseRedirect(reverse('login:profile'))

def delete_status(request, id):
    npm = get_data_human(request,'kode_identitas')
    human = Human.objects.get(npm = npm)
    status = human.status_set.filter(pk=id)
    status.delete()
    return HttpResponseRedirect(reverse('login:profile'))

profiles/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
import requests
from friend.models import Expertise, Friend
from login.models import Human
import json
# Create your views here.
response = {}

def index(request):
    set_data_for_session(response, request)
    return render(request, 'profiles/profile.html', response)

def set_data_for_session(res, request):
    response['author'] = request.session['user_login']
    response['kode_identitas'] = request.session['kode_identitas']
    # response['name'] = request.session['name']
    if 'email' in request.session:
        response['name'] = request.session['name']
        response['email'] = request.session['email']
        response['linkedin'] = request.session['linkedin']
        response['picture'] = request.session['picture']
        response['score'] = request.session['score']
    else:
        response['picture'] = "https://www.idlidu.com/Content/images/default.png"
        response['score'] = "1"

    expertise = get_expertise_from_database(request)
    response['expertise'] = expertise
    response['numOfExpertise'] = expertise.count()

def edit_profile(request):
    set_data_for_session(response, request)
    return render(request, 'profiles/editProfile.html', response)

# def list_status(request):
#     #  Implement this function by yourself
#     get_data_session(request)
#     status = []
#     if get_data_human(request, 'user_login'):
#         status = get_my_message_from_database(request)
#     print(status)
#     response['status'] = status

def get_expertise_from_database(request):
    resp = []
    # npm = get_data_human(request, 'kode_identitas')
    npm = request.session['kode_identitas']
    human = Human.objects.get(npm=npm)
    expertise = human.expertise.all()
    return expertise

# def get_data_session(request):
#     if get_data_human(request, 'user_login'):
#         response['author'] = get_data_human(request, 'user_login')
#
# def get_data_human(request, tipe):
#     data = None
#     if tipe == "user_login" and 'user_login' in request.session:
#         data = request.session['user_login']
#     elif tipe == "kode_identitas" and 'kode_identitas' in request.session:
#         data = request.session['kode_identitas']
#     return data

def delete_expertise(request, id):
    npm = request.session['kode_identitas']
    human = Human.objects.get(npm = npm)
    expertise = human.expertise.filter(pk=id)
    expertise.delete()
    return HttpResponseRedirect(reverse('profile:edit_profile'))

@csrf_exempt
def save_profile_before(request):
    if request.method == 'POST':
        request.session['score'] = request.POST['score']
        response['score'] = request.session['score']

        expertise = json.loads(request.POST['expertise']) #array of expertise
        level = json.loads(request.POST['level']) #array of level
        npm = request.session['kode_identitas']
        human = Human.objects.get(npm=npm)
        human.expertise.all().delete()
        for i in range(len(expertise)):
            human.expertise.add(Expertise.objects.create(name=expertise[i], level=level[i], color=level[i]))

        human.score = request.session['score']
        human.save()

    return JsonResponse({'redirect_url': '/login/'})

@csrf_exempt
def get_profile(request):
    if request.method == 'GET':
        response['score'] = request.session['score']
        return JsonResponse(response)

@csrf_exempt
def save_profile(request):
    if request.method == 'POST':
        request.session['name'] = request.POST['name']
        request.session['email'] = request.POST['email']
        request.session['linkedin'] = request.POST['linkedin']
        request.session['picture'] = request.POST['picture']
        request.session['score'] = request.POST['score']
        response['name'] = request.session['name']
        response['email'] = request.session['email']
        response['linkedin'] = request.session['linkedin']
        response['picture'] = request.session['picture']
        response['score'] = request.session['score']

        expertise = json.loads(request.POST['expertise']) #array of expertise
        level = json.loads(request.POST['level']) #array of level
        npm = request.session['kode_identitas']
        human = Human.objects.get(npm=npm)
        human.expertise.all().delete()
        for i in range(len(expertise)):
            human.expertise.add(Expertise.objects.create(name=expertise[i], level=level[i], color=level[i]))

        human.name = request.session['name']
        human.email = request.session['email']
        human.linkedin = request.session['linkedin']
        human.picture = request.session['picture']
        human.score = request.session['score']
        human.save()

    return JsonResponse({'redirect_url': '/login/'})

login/templates/login/session/login.html
{% extends "login/layout/base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="judul">
                <h1> Halaman Login </h1>
                <p class="text-info"> Gunakan <b> akun SSO </b> untuk login </p>
            </div>
            <form action="{% url 'login:auth_login' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="username"> Your username </label>
                    <input type="text" id="username" name="username" required>
                </p>
                <p>
                    <label for="password"> Your password </label>
                    <input type="password" id="password" name="password" required>
                </p>
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
{% endblock %}

login/templates/login/session/profile.html
{% extends "login/layout/base.html" %}
{% block content %}
<!-- Content Here -->
<div class="pojok-kanan">
</div>
<div class="wrapper">
<br>
<h4> Welcome, {{author}} </h4>
<div class="panel panel-default">
    <!-- <div class="panel-heading">

    </div> -->
    <div class="panel-body">
        <img id="img" class="img-circle" src={{picture}} style="height:120px;widht:120px;float:left;margin-right:30px;"/>
        <br>
        <p>Total Status: {{jumlah_status}}</p>
        <p>Last Status : {{stat_last}}</p>
    </div>
    <div class="panel-footer">
        <a href="{% url 'profile:edit_profile' %}" class="btn btn-info"> Edit Profile </a>
    </div>
</div>

<div>
    <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified" role="tablist">
        <li class="active">
            <a href="#status" aria-controls="home" role="tab" data-toggle="tab"> Status </a>
        </li>
        <li role="presentation">
            <a href="#history" aria-controls="settings" role="tab" data-toggle="tab"> History </a>
        </li>
        <li role="presentation">
            <a href="#profile" aria-controls="settings" role="tab" data-toggle="tab"> Profile </a>
        </li>
        <li role="presentation">
            <a href="#friend" aria-controls="settings" role="tab" data-toggle="tab"> Friend </a>
        </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active" id="status">
            {% include 'login/status.html' %}
        </div>
        <div role="tabpanel" class="tab-pane fade" id="profile">
            <object type="text/html" data="/profile"  width='100%' height="600px" style="overflow:auto;">
            </object>
        </div>
        <div role="tabpanel" class="tab-pane fade" id="friend">
            <object type="text/html" data="/friend"  width="100%" height="600px" style="overflow:auto">
            </object>
        </div>
        <div role="tabpanel" class="tab-pane fade" id="history">
            <object type="text/html" data="/history"  width="100%" height="600px" style="overflow:auto">
            </object>
        </div>

    </div>
</div>
</div>

<script>
    $(".dropdown").html(
        '<a href="#" class="dropdown-toggle" data-toggle="dropdown">'
        + '<img src={{picture}} class="profile-image img-circle" style="height:30px;width:30px"><b class="caret"></b></a>'
        + '<div class="dropdown-content">'
        + '<a href="{% url "login:auth_logout" %}" onclick="return confirm("Logout?")"> Logout </a>'
        + '</div>'
    )
</script>

{% endblock %}